// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: feed_follows.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createFeedFollow = `-- name: CreateFeedFollow :one
INSERT INTO feed_follows (id, user_id, feed_id) 
VALUES ($1, $2, $3) 
RETURNING id, feed_id, user_id, created_at, updated_at
`

type CreateFeedFollowParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
	FeedID uuid.UUID
}

func (q *Queries) CreateFeedFollow(ctx context.Context, arg CreateFeedFollowParams) (FeedFollow, error) {
	row := q.db.QueryRowContext(ctx, createFeedFollow, arg.ID, arg.UserID, arg.FeedID)
	var i FeedFollow
	err := row.Scan(
		&i.ID,
		&i.FeedID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFeedFollowByID = `-- name: DeleteFeedFollowByID :exec
DELETE FROM feed_follows 
WHERE user_id = $1 AND feed_id = $2
`

type DeleteFeedFollowByIDParams struct {
	UserID uuid.UUID
	FeedID uuid.UUID
}

func (q *Queries) DeleteFeedFollowByID(ctx context.Context, arg DeleteFeedFollowByIDParams) error {
	_, err := q.db.ExecContext(ctx, deleteFeedFollowByID, arg.UserID, arg.FeedID)
	return err
}

const deleteFeedFollowsByUserID = `-- name: DeleteFeedFollowsByUserID :exec
DELETE FROM feed_follows 
WHERE user_id = $1
`

func (q *Queries) DeleteFeedFollowsByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteFeedFollowsByUserID, userID)
	return err
}
